### ISSUE TITLE
Incorrect tabTrigger for json.NewEncoder snippet

### ISSUE THREAD

**Issue by nooproblem** [ccirello/sublime-gosnippets#1]
json.New**Decoder**:

var ${1:data} ${2:interface{}}
if err := json.New**Encoder**(${3:w}).**Encode**(&${1:data}); err != nil {
    ${4:log.Fatal(err)}
}

**Comment by ccirello** [comment]
Sorry for this bug. I shall fix it asap.

**Comment by ccirello** [comment]
Fixed https://github.com/ccirello/sublime-gosnippets/commit/064f7afed53e2fe2a99990d403a869da4806acbd
